<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}"><title>Iniciar sesi&oacute;n &middot; TG Creative Hub</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen overflow-x-hidden bg-[#080c13] text-white antialiased">
<main class="grid min-h-screen lg:grid-cols-[42%_58%]">
    <section class="relative hidden overflow-hidden border-r border-white/10 bg-[#090e16] lg:flex lg:flex-col lg:justify-between lg:px-[clamp(3rem,8vw,7.5rem)] lg:py-16">
        <div class="absolute inset-0 opacity-70" aria-hidden="true"><div class="absolute -right-24 -top-16 h-[34rem] w-[34rem] rounded-full border border-red-500/20 [transform:rotate(32deg)]"></div><div class="absolute -bottom-32 left-1/3 h-[40rem] w-[28rem] -skew-x-12 bg-gradient-to-tr from-red-950/40 via-slate-900/20 to-transparent"></div></div>
        <div class="relative z-10 pt-8"><div class="flex items-center gap-5"><img src="{{ asset('02-TG-Logo.png') }}" alt="Total Ground" class="h-28 w-32 object-contain"><div><p class="text-5xl font-light tracking-tight">TOTAL</p><p class="text-5xl font-light tracking-tight">GROUND</p><p class="mt-3 text-xl tracking-[.34em] text-slate-200">TG CREATIVE HUB</p></div></div><div class="mt-12 h-0.5 w-16 bg-red-500"></div><h1 class="mt-12 max-w-md text-4xl font-semibold leading-tight xl:text-5xl">Un espacio para <span class="text-red-500">crear, colaborar</span> y crecer.</h1><p class="mt-8 max-w-md text-lg leading-8 text-slate-400">Gestiona tus solicitudes creativas, seguimientos y entregables de forma simple, organizada y eficiente.</p></div>
        <div class="relative z-10 grid max-w-xl grid-cols-3 overflow-hidden rounded-2xl border border-white/10 bg-slate-950/55"><div class="p-6 text-center"><p class="text-3xl text-red-500">&#9671;</p><p class="mt-3 font-semibold">Seguro</p><p class="mt-2 text-xs text-slate-400">Tus datos protegidos</p></div><div class="border-x border-white/10 p-6 text-center"><p class="text-3xl text-red-500">&#9827;</p><p class="mt-3 font-semibold">Colaborativo</p><p class="mt-2 text-xs text-slate-400">Equipos conectados</p></div><div class="p-6 text-center"><p class="text-3xl text-red-500">&#9671;</p><p class="mt-3 font-semibold">Eficiente</p><p class="mt-2 text-xs text-slate-400">Procesos optimizados</p></div></div>
    </section>
    <section class="relative flex min-h-screen items-center justify-center px-5 py-10 sm:px-10 lg:px-[clamp(3rem,8vw,8rem)]"><div class="absolute right-0 top-0 h-[36rem] w-[36rem] rounded-full bg-red-700/20 blur-[110px]" aria-hidden="true"></div><div class="relative z-10 w-full max-w-2xl [perspective:1600px]"><div id="login-card" class="relative min-h-[720px] w-full transition-transform duration-700 [transform-style:preserve-3d]">
        <div class="absolute inset-0 rounded-[26px] border border-slate-700/80 bg-[#111722]/95 p-7 shadow-[0_0_60px_rgba(227,6,19,.22)] [backface-visibility:hidden] sm:p-12 lg:p-16">
            <p class="text-sm font-medium uppercase tracking-wide text-red-500">Acceso corporativo</p><h2 class="mt-5 text-4xl font-bold tracking-tight sm:text-5xl">Bienvenido</h2><p class="mt-4 text-lg text-slate-400">Inicia sesi&oacute;n con tu cuenta corporativa.</p>
            @if(session('status'))<div class="mt-6 rounded border border-green-500/40 bg-green-500/10 p-3 text-sm">{{ session('status') }}</div>@endif
            @if($errors->any())<div class="mt-6 rounded border border-red-500/50 bg-red-950/40 p-4 text-sm" role="alert"><p class="font-semibold">No fue posible iniciar sesi&oacute;n</p><p class="mt-1 text-slate-300">Verifica tus datos e int&eacute;ntalo nuevamente.</p></div>@endif
            <form method="POST" action="{{ route('login.store') }}" class="mt-10 space-y-7" x-data="{ submitting: false }" @submit="submitting = true">@csrf
                <div><label for="email" class="block text-base font-semibold">Correo corporativo <span class="text-red-500">*</span></label><input id="email" name="email" type="email" value="{{ old('email') }}" required autofocus autocomplete="email" placeholder="nombre@totalground.com" class="mt-3 min-h-16 w-full rounded-xl border border-slate-600 bg-slate-950/50 px-4 text-base outline-none focus:border-red-500"></div>
                <div><label for="password" class="block text-base font-semibold">Contrase&ntilde;a <span class="text-red-500">*</span></label><div class="mt-3 flex min-h-16 rounded-xl border border-slate-600 bg-slate-950/50 focus-within:border-red-500"><input id="password" name="password" type="password" required autocomplete="current-password" class="min-w-0 flex-1 bg-transparent px-4 text-base outline-none"><button type="button" class="px-4 text-slate-400 hover:text-white" onclick="togglePasswordVisibility(this)" aria-label="Mostrar contrase&ntilde;a">&#128065;</button></div></div>
                <div class="flex flex-wrap items-center justify-between gap-4"><label class="inline-flex min-h-11 items-center gap-3 text-base text-slate-400"><input name="remember" type="checkbox" class="h-5 w-5 accent-red-600"> Mantener sesi&oacute;n iniciada</label><a href="{{ route('password.request') }}" class="text-base font-semibold text-red-500 hover:text-red-300">&iquest;Olvidaste tu contrase&ntilde;a?</a></div>
                <button type="submit" x-bind:disabled="submitting" class="flex min-h-16 w-full items-center justify-center gap-5 rounded-xl bg-red-600 text-lg font-bold hover:bg-red-500"><span x-show="!submitting">Iniciar sesi&oacute;n <span class="ml-4 text-2xl">&#10132;</span></span><span x-show="submitting" x-cloak>Iniciando sesi&oacute;n...</span></button>
            </form>
            <p class="mt-8 text-center text-base text-slate-400">&iquest;Necesitas ayuda? Contacta a <a href="mailto:soporte@totalground.com" class="text-red-500 hover:text-red-300">soporte</a></p>
            <button type="button" onclick="flipLoginCard(true)" class="mt-8 flex min-h-14 w-full items-center justify-center gap-3 rounded-xl border border-red-500/60 bg-red-500/5 text-base font-semibold text-red-400 transition hover:bg-red-500/15 hover:text-red-300">Acceso al sistema de tickets <span class="text-xl">&#10132;</span></button>
        </div>
        <div class="absolute inset-0 overflow-y-auto rounded-[26px] border border-slate-700/80 bg-[#111722]/95 p-6 text-slate-900 shadow-[0_0_60px_rgba(227,6,19,.22)] [backface-visibility:hidden] [transform:rotateY(180deg)] sm:p-10">
            <div class="mx-auto max-w-md rounded-2xl bg-white p-6 shadow-lg sm:p-8">
                <img src="{{ asset('tickets/total.webp') }}" alt="Total Ground" class="mx-auto h-12 w-auto object-contain">
                <h2 class="mt-5 flex items-center justify-center gap-3 text-3xl font-bold text-red-600"><img src="{{ asset('tickets/soporte.png') }}" alt="" class="h-12 w-12 object-contain">Sistema de Tickets</h2>
                <div class="mt-7 grid grid-cols-2 border-b border-slate-300"><button type="button" id="ticket-tab-collaborator" onclick="showTicketTab('collaborator')" class="border-b-4 border-red-500 py-3 font-medium text-red-600">Colaborador</button><button type="button" id="ticket-tab-admin" onclick="showTicketTab('admin')" class="border-b-4 border-transparent py-3 font-medium text-slate-500">Administrador</button></div>
                <form id="ticket-collaborator-form" class="mt-8 space-y-5" onsubmit="loginTickets(event, 'collaborator')"><label for="ticket-department" class="block font-semibold">Selecciona tu departamento:</label><select id="ticket-department" required class="w-full rounded-lg border-2 border-slate-300 bg-white px-3 py-3 outline-none focus:border-red-500"><option value="">-- Selecciona un departamento --</option><option>Administraci&oacute;n</option><option>Torno</option><option>Producci&oacute;n</option><option>Almac&eacute;n de materia prima</option><option>Almac&eacute;n de instalaciones</option><option>Almac&eacute;n de producto terminado</option><option>Log&iacute;stica</option><option>Sistemas - Dise&ntilde;o - Multimedia</option><option>Electr&oacute;nica</option><option>Direcci&oacute;n Comercial / Mercadotecnia</option><option>Ventas Internas</option><option>Ventas Externas</option><option>CDMX</option><option>Recepci&oacute;n</option><option>Proyectos Especiales</option></select><button type="submit" class="w-full rounded-lg bg-red-600 py-3.5 font-bold text-white transition hover:bg-red-500">Ingresar</button></form>
                <form id="ticket-admin-form" class="mt-8 hidden space-y-5" onsubmit="loginTickets(event, 'admin')"><label class="block font-semibold">Usuario:</label><input id="ticket-username" required class="w-full rounded-lg border-2 border-slate-300 px-3 py-3 outline-none focus:border-red-500"><label class="block font-semibold">Contrase&ntilde;a:</label><div class="flex rounded-lg border-2 border-slate-300 focus-within:border-red-500"><input id="ticket-password" type="password" required class="min-w-0 flex-1 rounded-lg px-3 py-3 outline-none"><button type="button" onclick="toggleTicketPassword(this)" class="px-3 text-slate-500" aria-label="Mostrar contraseña">&#128065;</button></div><button type="submit" class="w-full rounded-lg bg-red-600 py-3.5 font-bold text-white transition hover:bg-red-500">Ingresar</button></form>
                <p id="ticket-login-error" class="mt-4 hidden text-center text-sm font-medium text-red-600"></p>
                <button type="button" onclick="flipLoginCard(false)" class="mt-7 w-full text-sm text-slate-500 hover:text-red-600">&#8592; Volver al acceso corporativo</button>
            </div>
        </div>
    </div></div><footer class="absolute bottom-6 left-0 right-0 text-center text-xs text-slate-500">Total Ground &copy; 2026 &middot; Todos los derechos reservados</footer></section>
</main>
<script>
function togglePasswordVisibility(button){const input=document.getElementById('password');const visible=input.type==='text';input.type=visible?'password':'text';button.setAttribute('aria-label',visible?'Mostrar contrase&ntilde;a':'Ocultar contrase&ntilde;a');}
function flipLoginCard(showTickets){const card=document.getElementById('login-card');if(card)card.style.transform=showTickets?'rotateY(180deg)':'rotateY(0deg)';}
function showTicketTab(tab){const collaborator=tab==='collaborator';document.getElementById('ticket-collaborator-form').classList.toggle('hidden',!collaborator);document.getElementById('ticket-admin-form').classList.toggle('hidden',collaborator);document.getElementById('ticket-tab-collaborator').className=collaborator?'border-b-4 border-red-500 py-3 font-medium text-red-600':'border-b-4 border-transparent py-3 font-medium text-slate-500';document.getElementById('ticket-tab-admin').className=!collaborator?'border-b-4 border-red-500 py-3 font-medium text-red-600':'border-b-4 border-transparent py-3 font-medium text-slate-500';}
function toggleTicketPassword(button){const input=document.getElementById('ticket-password');const visible=input.type==='text';input.type=visible?'password':'text';button.setAttribute('aria-label',visible?'Mostrar contraseña':'Ocultar contraseña');}
async function loginTickets(event,type){event.preventDefault();const error=document.getElementById('ticket-login-error');error.classList.add('hidden');const payload=type==='collaborator'?{department:document.getElementById('ticket-department').value}:{username:document.getElementById('ticket-username').value,password:document.getElementById('ticket-password').value};const action=type==='collaborator'?'login-collaborator':'login-admin';try{const response=await fetch('/tickets/api/auth.php?action='+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(data.success){window.location.href='/tickets/index.php?page=dashboard';}else{error.textContent=data.error||'No fue posible iniciar sesi&oacute;n';error.classList.remove('hidden');}}catch(e){error.textContent='No fue posible conectar con el sistema de tickets.';error.classList.remove('hidden');}}
</script>
</body>
</html>
